# Generated by Django 3.1.6 on 2021-04-22 00:28

from django.conf import settings
from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20210420_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(main_app.models.get_sentinel_user), to='auth.user'),
            preserve_default=False,
        ),
    ]
